# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QWidget)
import logo_rc

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowFlags(Qt.WindowType.Window | Qt.WindowType.CustomizeWindowHint | Qt.WindowType.WindowMinimizeButtonHint | Qt.WindowType.WindowCloseButtonHint)

        MainWindow.resize(900, 750)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(270, -20, 1366, 768))
        self.stackedWidget.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.login = QWidget()
        self.login.setObjectName(u"login")
        
        self.password = QLineEdit(self.login)
        self.password.setObjectName(u"password")
        self.password.setGeometry(QRect(40, 330, 281, 31))
        self.password.setFocusPolicy(Qt.ClickFocus)
        self.password.setContextMenuPolicy(Qt.PreventContextMenu)
        self.password.setStyleSheet(u"")
        self.password.setFrame(True)
        self.password.setEchoMode(QLineEdit.Password)
        self.password.setCursorPosition(0)
        self.password.setAlignment(Qt.AlignCenter)
        self.password.setDragEnabled(False)
        self.password.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.password.setClearButtonEnabled(True)
        self.label_2 = QLabel(self.login)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(40, 160, 171, 16))
        font = QFont()
        font.setFamilies([u"Calibri Light"])
        self.label_2.setFont(font)
        self.email = QLineEdit(self.login)
        self.email.setObjectName(u"email")
        self.email.setGeometry(QRect(40, 230, 281, 31))
        self.email.setFocusPolicy(Qt.ClickFocus)
        self.email.setContextMenuPolicy(Qt.PreventContextMenu)
        self.email.setStyleSheet(u"")
        self.email.setFrame(True)
        self.email.setEchoMode(QLineEdit.Normal)
        self.email.setCursorPosition(0)
        self.email.setAlignment(Qt.AlignCenter)
        self.email.setDragEnabled(False)
        self.email.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.email.setClearButtonEnabled(True)
        self.label_3 = QLabel(self.login)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(40, 200, 111, 16))
        font1 = QFont()
        font1.setFamilies([u"Calibri Light"])
        font1.setPointSize(9)
        font1.setBold(False)
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.login)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(40, 300, 111, 16))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.login)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 270, 261, 16))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.login)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 370, 261, 16))
        self.label_6.setFont(font1)
        self.logintext = QLabel(self.login)
        self.logintext.setObjectName(u"logintext")
        self.logintext.setGeometry(QRect(40, 120, 181, 31))
        font2 = QFont()
        font2.setFamilies([u"MS Shell Dlg 2"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.logintext.setFont(font2)
        self.logintext.setInputMethodHints(Qt.ImhNone)
        self.logintext.setFrameShadow(QFrame.Plain)
        self.logintext.setText(u"Log into VigilEye")
        self.logintext.setTextFormat(Qt.AutoText)
        self.pushButton = QPushButton(self.login)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(50, 410, 91, 31))
        self.pushButton.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n"
"                                 ")
        self.pushButton.setCheckable(False)
        self.pushButton_forget = QPushButton(self.login)
        self.pushButton_forget.setObjectName(u"pushButton")
        self.pushButton_forget.setGeometry(QRect(150, 410, 110, 31))
        self.pushButton_forget.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n"
"                                 ")
        self.pushButton_forget.setCheckable(False)
        
        self.stackedWidget.addWidget(self.login)
        self.signup = QWidget()
        self.signup.setObjectName(u"signup")
        self.pushButton_6 = QPushButton(self.signup)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(50, 510, 91, 31))
        self.pushButton_6.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n"
"                                 ")
        self.pushButton_6.setCheckable(False)
        self.email_5 = QLineEdit(self.signup)
        self.email_5.setObjectName(u"email_5")
        self.email_5.setGeometry(QRect(50, 170, 281, 31))
        self.email_5.setFocusPolicy(Qt.ClickFocus)
        self.email_5.setContextMenuPolicy(Qt.PreventContextMenu)
        self.email_5.setStyleSheet(u"")
        self.email_5.setFrame(True)
        self.email_5.setEchoMode(QLineEdit.Normal)
        self.email_5.setCursorPosition(0)
        self.email_5.setAlignment(Qt.AlignCenter)
        self.email_5.setDragEnabled(False)
        self.email_5.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.email_5.setClearButtonEnabled(True)
        self.label_14 = QLabel(self.signup)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(50, 230, 111, 16))
        self.label_14.setFont(font1)
        self.logintext_3 = QLabel(self.signup)
        self.logintext_3.setObjectName(u"logintext_3")
        self.logintext_3.setGeometry(QRect(50, 70, 181, 31))
        self.logintext_3.setFont(font2)
        self.logintext_3.setInputMethodHints(Qt.ImhNone)
        self.logintext_3.setFrameShadow(QFrame.Plain)
        self.logintext_3.setText(u"Create new user")
        self.logintext_3.setTextFormat(Qt.AutoText)
        self.label_13 = QLabel(self.signup)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(50, 110, 171, 16))
        self.label_13.setFont(font)
        self.email_4 = QLineEdit(self.signup)
        self.email_4.setObjectName(u"email_4")
        self.email_4.setGeometry(QRect(50, 260, 281, 31))
        self.email_4.setFocusPolicy(Qt.ClickFocus)
        self.email_4.setContextMenuPolicy(Qt.PreventContextMenu)
        self.email_4.setStyleSheet(u"")
        self.email_4.setFrame(True)
        self.email_4.setEchoMode(QLineEdit.Normal)
        self.email_4.setCursorPosition(0)
        self.email_4.setAlignment(Qt.AlignCenter)
        self.email_4.setDragEnabled(False)
        self.email_4.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.email_4.setClearButtonEnabled(True)
        self.password_4 = QLineEdit(self.signup)
        self.password_4.setObjectName(u"password_4")
        self.password_4.setGeometry(QRect(50, 350, 281, 31))
        self.password_4.setFocusPolicy(Qt.ClickFocus)
        self.password_4.setContextMenuPolicy(Qt.PreventContextMenu)
        self.password_4.setStyleSheet(u"")
        self.password_4.setFrame(True)
        self.password_4.setEchoMode(QLineEdit.Password)
        self.password_4.setCursorPosition(0)
        self.password_4.setAlignment(Qt.AlignCenter)
        self.password_4.setDragEnabled(False)
        self.password_4.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.password_4.setClearButtonEnabled(True)
        self.label_15 = QLabel(self.signup)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 320, 111, 16))
        self.label_15.setFont(font1)
        self.password_5 = QLineEdit(self.signup)
        self.password_5.setObjectName(u"password_5")
        self.password_5.setGeometry(QRect(50, 440, 281, 31))
        self.password_5.setFocusPolicy(Qt.ClickFocus)
        self.password_5.setContextMenuPolicy(Qt.PreventContextMenu)
        self.password_5.setStyleSheet(u"")
        self.password_5.setFrame(True)
        self.password_5.setEchoMode(QLineEdit.Password)
        self.password_5.setCursorPosition(0)
        self.password_5.setAlignment(Qt.AlignCenter)
        self.password_5.setDragEnabled(False)
        self.password_5.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.password_5.setClearButtonEnabled(True)
        self.label_19 = QLabel(self.signup)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(50, 410, 111, 16))
        self.label_19.setFont(font1)
        self.label_18 = QLabel(self.signup)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(50, 140, 111, 16))
        self.label_18.setFont(font1)
        self.stackedWidget.addWidget(self.signup)

        self.forget = QWidget()
        self.forget.setObjectName(u"forget")
        self.widget_16 = QWidget(self.forget)
        self.widget_16.setObjectName(u"widget_16")
        self.widget_16.setGeometry(QRect(0, 0, 861, 851))
        self.widget_16.setStyleSheet(u"background-color: rgb(230, 230, 230);")
        self.password_verify = QLineEdit(self.widget_16)
        self.password.setObjectName(u"password_verify")
        self.password_verify.setGeometry(QRect(40, 330, 281, 31))
        self.password_verify.setFocusPolicy(Qt.ClickFocus)
        self.password_verify.setContextMenuPolicy(Qt.PreventContextMenu)
        self.password_verify.setStyleSheet(u"")
        self.password_verify.setFrame(True)
        self.password_verify.setCursorPosition(0)
        self.password_verify.setAlignment(Qt.AlignCenter)
        self.password_verify.setDragEnabled(False)
        self.password_verify.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.password_verify.setClearButtonEnabled(True)
        self.label_21 = QLabel(self.widget_16)
        self.label_21.setObjectName(u"label_2")
        self.label_21.setGeometry(QRect(40, 160, 171, 16))
        self.label_21.setFont(font)
        self.email_verify = QLineEdit(self.widget_16)
        self.email_verify.setObjectName(u"email")
        self.email_verify.setGeometry(QRect(40, 230, 281, 31))
        self.email_verify.setFocusPolicy(Qt.ClickFocus)
        self.email_verify.setContextMenuPolicy(Qt.PreventContextMenu)
        self.email_verify.setStyleSheet(u"")
        self.email_verify.setFrame(True)
        self.email_verify.setEchoMode(QLineEdit.Normal)
        self.email_verify.setCursorPosition(0)
        self.email_verify.setAlignment(Qt.AlignCenter)
        self.email_verify.setDragEnabled(False)
        self.email_verify.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.email_verify.setClearButtonEnabled(True)
        self.label_31 = QLabel(self.widget_16)
        self.label_31.setObjectName(u"label_3")
        self.label_31.setGeometry(QRect(40, 200, 111, 16))
        self.label_31.setFont(font1)
        self.label_41 = QLabel(self.widget_16)
        self.label_41.setObjectName(u"label_4")
        self.label_41.setGeometry(QRect(40, 300, 111, 16))
        self.label_41.setFont(font1)

        self.password_verify.setInputMask("")
        self.password_verify.setText("")
        self.password_verify.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your verification code...", None))
        self.email_verify.setInputMask("")
        self.email_verify.setText("")
        self.email_verify.setPlaceholderText(QCoreApplication.translate("MainWindow", u"vigileye@example.com", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"EMAIL ADDRESS", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"VERIFICATION CODE", None))

        self.pushButton_696 = QPushButton(self.widget_16)
        self.pushButton_696.setObjectName(u"pushButton_696")
        self.pushButton_696.setGeometry(QRect(100, 420, 93, 28))
        self.pushButton_696.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n")
        self.pushButton_696.setText(QCoreApplication.translate("MainWindow", u"Verify", None))
        self.pushButton_6969 = QPushButton(self.widget_16)
        self.pushButton_6969.setObjectName(u"pushButton_696")
        self.pushButton_6969.setGeometry(QRect(200, 420, 93, 28))
        self.pushButton_6969.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n")
        self.pushButton_6969.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_69696 = QPushButton(self.widget_16)
        self.pushButton_69696.setObjectName(u"pushButton_696")
        self.pushButton_69696.setGeometry(QRect(330, 230, 93, 28))
        self.pushButton_69696.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n")
        self.pushButton_69696.setText(QCoreApplication.translate("MainWindow", u"Send Code", None))
        self.logintext2 = QLabel(self.widget_16)
        self.logintext2.setObjectName(u"logintext2")
        self.logintext2.setGeometry(QRect(40, 120, 181, 31))
        self.logintext2.setFont(font2)
        self.logintext2.setInputMethodHints(Qt.ImhNone)
        self.logintext2.setFrameShadow(QFrame.Plain)
        self.logintext2.setText(u"Forget Password")
        self.logintext2.setTextFormat(Qt.AutoText)

        self.label_66 = QLabel(self.widget_16)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(40, 370, 261, 16))
        self.label_66.setFont(font1)

        self.stackedWidget.addWidget(self.forget)


        self.sidebar_3 = QWidget(self.centralwidget)
        self.sidebar_3.setObjectName(u"sidebar_3")
        self.sidebar_3.setGeometry(QRect(0, 0, 271, 851))
        self.sidebar_3.setStyleSheet(u"background-color: rgb(0, 31, 63);")
        self.label_16 = QLabel(self.sidebar_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 180, 251, 261))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(0, 31, 63, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Active, QPalette.Base, brush1)
        palette.setBrush(QPalette.Active, QPalette.Window, brush1)
        brush2 = QBrush(QColor(255, 255, 255, 128))
        brush2.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush2)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush1)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush2)
#endif
        self.label_16.setPalette(palette)
        font3 = QFont()
        font3.setFamilies([u"Calibri"])
        font3.setPointSize(13)
        font3.setBold(True)
        self.label_16.setFont(font3)
        self.label_16.setCursor(QCursor(Qt.ArrowCursor))
        self.label_16.setLayoutDirection(Qt.LeftToRight)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_query = QLabel(self.signup)
        self.label_query.setObjectName(u"label_5")
        self.label_query.setGeometry(QRect(180, 520, 500, 16))
        self.label_query.setFont(font1)
        

        self.logo_3 = QLabel(self.sidebar_3)
        self.logo_3.setObjectName(u"logo_3")
        self.logo_3.setGeometry(QRect(70, 50, 150, 70))
        self.logo_3.setPixmap(QPixmap(u"vigileye_logo-removebg.png"))
        self.logo_3.setScaledContents(True)
        
        self.pushButton_2 = QPushButton(self.sidebar_3)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(40, 470, 91, 31))
        self.pushButton_2.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n"
"                                 ")
        self.pushButton_2.setCheckable(False)
        self.pushButton_7 = QPushButton(self.sidebar_3)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(140, 470, 91, 31))
        self.pushButton_7.setStyleSheet(u"background-color: black;\n"
"color: white;\n"
"border-radius: 10px;\n"
"                                 ")
        self.pushButton_7.setCheckable(False)
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.pushButton, self.pushButton_6)

        self.retranslateUi(MainWindow)

        


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"VigilEye-Login", None))
        self.login.setWindowTitle(QCoreApplication.translate("MainWindow", u"VigilEye-Login", None))
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password...", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Enter your login details here", None))
        self.email.setInputMask("")
        self.email.setText("")
        self.email.setPlaceholderText(QCoreApplication.translate("MainWindow", u"vigileye@example.com", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"EMAIL ADDRESS", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"PASSWORD", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.pushButton_forget.setText(QCoreApplication.translate("MainWindow", u"Forget Password", None))

        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"Sign up", None))
        self.email_5.setInputMask("")
        self.email_5.setText("")
        self.email_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter name", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"EMAIL ADDRESS", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Enter your user details here", None))
        self.email_4.setInputMask("")
        self.email_4.setText("")
        self.email_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"vigileye@example.com", None))
        self.password_4.setInputMask("")
        self.password_4.setText("")
        self.password_4.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password...", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"PASSWORD", None))
        self.password_5.setInputMask("")
        self.password_5.setText("")
        self.password_5.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Enter your password...", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"CONFIRM PASSWORD", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"FULL NAME", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Welcome to VigilEye \n"
"Where Innovation Meets Vigilance!", None))
        self.logo_3.setText("")
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Login", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"Sign up", None))
    # retranslateUi

